#!/bin/bash

./s_chat_Linuxx86_64 5000 localhost 5000

# print_help() {
# 	echo "Incorrect number of arguments."
# 	echo "Usage: s-chat <src_port> <dst_host_name> <dst_port>"
# }

# if [[ $# -ne 3 ]]; then
# 	echo "Invalid number of arguments"
# 	echo
# 	print_help
# 	exit 1
# fi

# case "$(uname -m)" in
# 	"x86_64")
# 		./s_chat_Linuxx86_64 "$1" "$2" "$3"
# 		;;
# 	"armv7l")
# 		./s_chat_Linuxarmv7l "$1" "$2" "$3"
# 		;;
# 	"ppc")
# 		./s_chat_Linuxppc "$1" "$2" "$3"
# 		;;
# 	*)
# 		echo "Unknown value: $(uname -m)"
# 		echo
# 		exit 1
# 		;;
# esac
