#!/bin/bash

if [[ ! -e "results" ]]; then
    mkdir results
fi

run_test() {
    local numThreads=$1
    local numIterations=$2
    local output_file=$3
    echo "***** numThreads=$numThreads, numIterations=$numIterations *****" > "$output_file"
    echo "" >> "$output_file"
    echo "" >> "$output_file"
    ./mem-management-sim "$numThreads" "$numIterations" >> "$output_file"
	if [[ $? -ne 0 ]]; then
        echo "Error: mem-management-sim failed for numThreads=$numThreads, numIterations=$numIterations" >> "$output_file"
    fi
}

NUM_ITERATIONS=1000
NUM_THREADS=5

echo "Starting tests with constant iterations but varying threads"
for numThreads in {1..10}; do
	run_test "$numThreads" "$NUM_ITERATIONS" \
	"results/const_iter_threads_${numThreads}_iterations_${NUM_ITERATIONS}.txt" &
done



echo "Starting tests with constant threads but varying iterations"
for num_iterations in {1000..10000..1000}; do
	run_test "$NUM_THREADS" "$num_iterations" \
	"results/const_thread_threads_${NUM_THREADS}_iterations_${num_iterations}.txt" &
done

wait
echo "Tests complete."
