#!/bin/bash


echo "Test Constant Iterations but Varying Threads" > results.txt
echo "------------------" >> results.txt

numIterations=100

for numThreads in {1..10}; do
	echo "Running simulations with numThreads=$numThreads" >> results.txt
	for run in {1..5}
	do
		echo "Run $run, numThreads=$numThreads, numIterations=$numIterations"
		echo "Run $run, numThreads=$numThreads, numIterations=$numIterations" >> results.txt
		./mem-management-sim $numThreads $numIterations >> results.txt
		echo "" >> results.txt
	done
done

echo "------------------" >> results.txt
echo >> results.txt
